"""empty message

Revision ID: 6b3b7fc757ad
Revises: 6bc386d9d8f2
Create Date: 2022-04-15 06:54:38.589201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3b7fc757ad'
down_revision = '6bc386d9d8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=250), nullable=False),
    sa.Column('book_author', sa.String(length=250), nullable=False),
    sa.Column('book_ISBN', sa.String(length=35), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booket_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=250), nullable=False),
    sa.Column('book_author', sa.String(length=250), nullable=False),
    sa.Column('book_ISBN', sa.String(length=35), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcast_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podcast_title', sa.String(length=150), nullable=False),
    sa.Column('popcast_company', sa.String(length=150), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcast_listen_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podcast_title', sa.String(length=150), nullable=False),
    sa.Column('podcast_company', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=275), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_series_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_title', sa.String(length=150), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_title', sa.String(length=150), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_watchlist')
    op.drop_table('tv_series_favorites')
    op.drop_table('posts')
    op.drop_table('podcast_listen_list')
    op.drop_table('podcast_favorites')
    op.drop_table('booket_list')
    op.drop_table('book_favorites')
    # ### end Alembic commands ###
