"""empty message

Revision ID: e49459a5346c
Revises: ee1e2e131ebd
Create Date: 2022-04-14 20:46:31.246787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49459a5346c'
down_revision = 'ee1e2e131ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('user', sa.Column('short_bio', sa.String(length=160), nullable=True))
    op.add_column('user', sa.Column('long_bio', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'long_bio')
    op.drop_column('user', 'short_bio')
    op.drop_table('followers')
    # ### end Alembic commands ###
